#!/usr/bin/env node
/**
 * Builds the single injectable script for the phone-standalone build:
 *
 *   mobile/dist/agent.js  =  __PIXEL_WEB__ map
 *                          + mobile/src/server.js   (send/recv shim + HTTP/SSE)
 *                          + public/scripts/agent.js (UNMODIFIED desktop agent,
 *                                                      with offsets injected)
 *
 * Run AFTER the root `npm run build` (which compiles the agent to
 * public/scripts/agent.js and offsets to dist/offsets.js):
 *
 *   npm run build && node mobile/build.cjs
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const AGENT = path.join(ROOT, 'public', 'scripts', 'agent.js');
const OFFSETS = path.join(ROOT, 'dist', 'offsets.js');
const SERVER = path.join(__dirname, 'src', 'server.js');
const WEB_DIR = path.join(__dirname, 'web');
const OUT_DIR = path.join(__dirname, 'dist');
const OUT = path.join(OUT_DIR, 'agent.js');

function die(msg) { console.error('[mobile/build] ' + msg); process.exit(1); }

if (!fs.existsSync(AGENT)) die('public/scripts/agent.js missing — run `npm run build` first.');
if (!fs.existsSync(OFFSETS)) die('dist/offsets.js missing — run `npm run build` first.');
if (!fs.existsSync(SERVER)) die('mobile/src/server.js missing.');

// 1. inject offsets into a COPY of the compiled agent (same token scheme as
//    scripts/inject-offsets.cjs, which the desktop build uses for inj.js).
const off = require(OFFSETS);
const placeholders = {
  '/*xaOffset*/': off._xaOffset,
  '/*anOffset*/': off._anOffset,
  '/*eposOffset*/': off._eposOffset,
  '/*xaPatch*/': off._xaPatch,
  '/*anPatch*/': off._anPatch,
  '/*agentSyms*/': off._symbols,
  '/*libName*/': off._libName,
};
let agent = fs.readFileSync(AGENT, 'utf8');
let subs = 0;
for (const [token, value] of Object.entries(placeholders)) {
  const json = JSON.stringify(value);
  if (/['\\]/.test(json)) die(`offset value for ${token} contains a quote/backslash; cannot inline safely.`);
  const escaped = token.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  agent = agent.replace(new RegExp(escaped, 'g'), () => { subs++; return json; });
}
if (subs === 0) die('no offset placeholders were substituted — agent.js may be stale.');

// 2. embed web assets as a string map
const web = {};
for (const name of fs.readdirSync(WEB_DIR)) {
  web['/' + name] = fs.readFileSync(path.join(WEB_DIR, name), 'utf8');
}
const webDecl = 'var __PIXEL_WEB__ = ' + JSON.stringify(web) + ';\n';

// 3. concatenate (web map -> server shim -> agent)
const server = fs.readFileSync(SERVER, 'utf8');
const banner =
  '// Pixel Mobile — generated by mobile/build.cjs. Do not edit by hand.\n' +
  '// Inject on a rooted device with bundled frida-inject. See mobile/README.md.\n';

fs.mkdirSync(OUT_DIR, { recursive: true });
fs.writeFileSync(OUT, banner + webDecl + server + '\n' + agent, 'utf8');

const kb = (fs.statSync(OUT).size / 1024).toFixed(0);
console.log(`[mobile/build] wrote ${path.relative(ROOT, OUT)} (${subs} offset subs, ` +
            `${Object.keys(web).length} web assets, ${kb} KB)`);
